### ISSUE TITLE
Unwarp images only works for 8-bit images

### ISSUE THREAD

**Issue by SJCross** [SJCross/MIA#83]

**Comment by SJCross** [comment]
When running UnwarpImages module with an input image of type other than 8-bit we get the error:

java.lang.IllegalArgumentException: Wrong type for this stack
	at ij.ImagePlus.setProcessor(ImagePlus.java:611)
	at ij.ImagePlus.setProcessor(ImagePlus.java:597)
	at wbif.sjx.ModularImageAnalysis.Module.ImageProcessing.Stack.UnwarpImages.replaceStack(UnwarpImages.java:222)
	at wbif.sjx.ModularImageAnalysis.Module.ImageProcessing.Stack.UnwarpImages.process(UnwarpImages.java:288)
	at wbif.sjx.ModularImageAnalysis.Module.ImageProcessing.Stack.UnwarpImages.run(UnwarpImages.java:366)
	at wbif.sjx.ModularImageAnalysis.Module.Module.execute(Module.java:57)
	at wbif.sjx.ModularImageAnalysis.GUI.Layouts.GUI.evaluateModule(GUI.java:1262)
	at wbif.sjx.ModularImageAnalysis.GUI.ControlObjects.EvalButton.lambda$actionPerformed$1(EvalButton.java:116)
	at java.lang.Thread.run(Thread.java:748)
